spring:
  banner:
    location: classpath:/folderexample/banner.txt

  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: MonteroAlan
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto:  update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

